.libPaths(c('library', 'library', .libPaths()))
cat('=== check_build_tools(debug=TRUE) ===\n')
res <- tryCatch(pkgbuild::check_build_tools(debug = TRUE), error = function(e) paste("ERR:", conditionMessage(e)))
print(res)
cat('\n=== has_build_tools ===\n')
print(pkgbuild::has_build_tools(debug = TRUE))
cat('\n=== make/gcc in PATH from R perspective ===\n')
cat('make:', Sys.which('make'), '\n')
cat('gcc:', Sys.which('gcc'), '\n')
cat('g++:', Sys.which('g++'), '\n')
cat('\n=== Sys.getenv PATH (first 500 chars) ===\n')
cat(substr(Sys.getenv('PATH'), 1, 500), '\n')
